-- MySQL Script generated by MySQL Workbench
-- Thu Feb 13 15:55:59 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema qualigestdb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema qualigestdb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `qualigestdb` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ;
USE `qualigestdb` ;

-- -----------------------------------------------------
-- Table `qualigestdb`.`Usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `qualigestdb`.`Usuarios` (
  `id_usuario` INT NULL DEFAULT NULL AUTO_INCREMENT,
  `nome_completo` VARCHAR(255) NOT NULL,
  `nome_usuario` VARCHAR(100) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `senha` VARCHAR(255) NOT NULL,
  `foto_perfil` TEXT NULL DEFAULT NULL,
  `pontuacao` INT NULL DEFAULT 0,
  `tarefas_concluidas` INT NULL DEFAULT 0,
  PRIMARY KEY (`id_usuario`),
  UNIQUE INDEX (`nome_usuario` ASC) ,
  UNIQUE INDEX (`email` ASC) )
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `qualigestdb`.`Projetos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `qualigestdb`.`Projetos` (
  `id_projeto` INT NULL DEFAULT NULL AUTO_INCREMENT,
  `nome_projeto` VARCHAR(255) NOT NULL,
  `pontuacao_projeto` INT NULL,
  `id_usuario` INT NOT NULL,
  PRIMARY KEY (`id_projeto`),
  INDEX (`id_usuario` ASC) ,
  CONSTRAINT ``
    FOREIGN KEY (`id_usuario`)
    REFERENCES `qualigestdb`.`Usuarios` (`id_usuario`))
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `qualigestdb`.`ParticipantesProjeto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `qualigestdb`.`ParticipantesProjeto` (
  `id_usuario` INT NULL DEFAULT NULL,
  `id_projeto` INT NULL DEFAULT NULL,
  `is_lider` BOOLEAN NOT NULL DEFAULT FALSE,
  PRIMARY KEY (`id_usuario`, `id_projeto`),
  INDEX (`id_projeto` ASC),
  CONSTRAINT `fk_participante_usuario`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `qualigestdb`.`Usuarios` (`id_usuario`),
  CONSTRAINT `fk_participante_projeto`
    FOREIGN KEY (`id_projeto`)
    REFERENCES `qualigestdb`.`Projetos` (`id_projeto`)
)
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `qualigestdb`.`Tarefas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `qualigestdb`.`Tarefas` (
  `id_tarefa` INT NULL DEFAULT NULL AUTO_INCREMENT,
  `id_projeto` INT NOT NULL,
  `titulo` VARCHAR(255) NOT NULL,
  `descricao` TEXT NOT NULL,
  `data_inicio` DATE NOT NULL,
  `data_limite` DATE NOT NULL,
  `prioridade` ENUM('baixa', 'moderada', 'alta', 'imediato') NOT NULL DEFAULT 'moderada',
  `pontuacao_tarefa` INT NULL,
  `status` ENUM('agendado', 'em andamento', 'concluído', 'atrasado', 'cancelado') NULL DEFAULT 'agendado',
  PRIMARY KEY (`id_tarefa`),
  INDEX (`id_projeto` ASC) ,
  CONSTRAINT `fk_tarefa_projeto`
    FOREIGN KEY (`id_projeto`)
    REFERENCES `qualigestdb`.`Projetos` (`id_projeto`))
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `qualigestdb`.`ResponsaveisTarefa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `qualigestdb`.`ResponsaveisTarefa` (
  `id_tarefa` INT NULL DEFAULT NULL,
  `id_usuario` INT NULL DEFAULT NULL,
  PRIMARY KEY (`id_tarefa`, `id_usuario`),
  INDEX (`id_usuario` ASC) ,
  CONSTRAINT `fk_responsavel_tarefa`
    FOREIGN KEY (`id_tarefa`)
    REFERENCES `qualigestdb`.`Tarefas` (`id_tarefa`),
  CONSTRAINT `fk_responsavel_usuario`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `qualigestdb`.`Usuarios` (`id_usuario`))
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;